services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: pr_service_e2e
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - pgdata_e2e:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*' -c port=5432

volumes:
  pgdata_e2e: